# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import os
from pathlib import Path


# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter.constants import END


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


# Clear Submit Box
def clear_widget(event):
    if username_entry == window.focus_get() and username_entry.get() == 'Enter Username':
        username_entry.delete(0, END)
    elif password_entry == window.focus_get() and password_entry.get() == '********':
        password_entry.delete(0, END)


def repopulate_defaults(event):
    if username_entry != window.focus_get() and username_entry.get() == '':
        username_entry.insert(0, 'Enter Username')
    elif password_entry != window.focus_get() and password_entry.get() == '':
        password_entry.insert(0, '********')


window = Tk()

window.geometry("375x667")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=667,
    width=375,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)

image_image_1 = PhotoImage(
    file=relative_to_assets("background.png"))
image_1 = canvas.create_image(
    189.0,
    333.0,
    image=image_image_1
)

username_image = PhotoImage(
    file=relative_to_assets("user.png"))
username_bg = canvas.create_image(
    187.0,
    432.5,
    image=username_image

)
username_entry = Entry(
    bd=0,
    bg="#E7E7E7",
    highlightthickness=0
)
username_entry.place(
    x=66.5,
    y=409.0,
    width=241.0,
    height=45.0
)
username_entry.insert(0, 'Enter Username')
username_entry.bind("<FocusIn>", clear_widget)
username_entry.bind('<FocusOut>', repopulate_defaults)

password_image = PhotoImage(
    file=relative_to_assets("pass.png"))
password_bg = canvas.create_image(
    187.0,
    488.5,
    image=password_image
)
password_entry = Entry(
    bd=0,
    bg="#E7E7E7",
    highlightthickness=0
)
password_entry.place(
    x=66.5,
    y=465.0,
    width=241.0,
    height=45.0
)
password_entry.insert(0, '********')
password_entry.bind("<FocusIn>", clear_widget)
password_entry.bind('<FocusOut>', repopulate_defaults)

# def login_page():
#     if username_entry.get()=="user" and password_entry.get()=="pass":
#         print(username_entry.get())
#         print(password_entry.get())
#         window.destroy()
#         os.system(r"python GUI_Project\bedroom.py")
#     else:
#         window.destroy()
login_image = PhotoImage(
    file=relative_to_assets("login.png"))
login_btn = Button(
    image=login_image,
    borderwidth=0,
    highlightthickness=0,
    # command = login_page,
    # command= User(username_entry.get(),password_entry.get()).login_page,
    relief="flat"
)
login_btn.place(
    x=97.0,
    y=536.0,
    width=172.0,
    height=46.0
)


def adminset():
    window.destroy()
    os.system(r"python GUI_Project/adminset.py")


change_pass = PhotoImage(
    file=relative_to_assets("button_2.png"))
change_pass_btn = Button(
    image=change_pass,
    borderwidth=0,
    highlightthickness=0,
    command=adminset,
    relief="flat")
change_pass_btn.place(
    x=143.0,
    y=590.0,
    width=89.0,
    height=11.0
)
window.resizable(False, False)
window.mainloop()